version: '3.1'
services:
  postgres_db:
    image: postgres:latest
    restart: always
    env_file:
      - app.env
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
  pgview:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 5050:80
    env_file:
      - pgadmin.env
  app:
    restart: always
    build:
      dockerfile: app.Dockerfile
    env_file:
      - app.env
