# Use postgres/example user/password credentials
version: '3.1'
services:
  postgres_db:
    image: postgres
    restart: always
    env_file:
      - db.env
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
  pgview:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_PASSWORD: a
      PGADMIN_DEFAULT_EMAIL: a@a.com
  app:
    restart: always
    build:
      dockerfile: app.Dockerfile
    env_file:
      - app.env
